version: '3.7'
services:
  dbt:
    build:
      context: ./dbt_jumiascraper
      dockerfile: Dockerfile.dbt
      target: dbt-postgres
    container_name: dbt-jumiascraper
    volumes:
      - ./dbt_jumiascraper/.dbt:/root/.dbt
      - ./dbt_jumiascraper/dbt_project.yml:/usr/app/dbt/dbt_project.yml
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - phonesjumia
    command: "build"

  postgres:
    image: postgres:15
    container_name: jumiascraperdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./logs/pglogs:/var/log/postgresql
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - phonesjumia
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_destination=stderr"
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   env_file:
  #     - .env
  #   networks:
  #     - phonesjumia
  #   ports:
  #     - ${HOSTPORT}:${LOCALPORT}

networks:
  phonesjumia:
    name: phonesjumia
    driver: bridge
    # external: true

volumes:
  pgdata:
  pglogs: # ${DBT_PROFILES_DIR}
