name: Welcome
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: Welcome
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install PyGithub
  
      - name: Get Issue Number
        id: get_issue_number
        run: |
          echo "::set-output name=issueNumber::${{ github.event.pull_request.number }}"

      - name: Check contribution history
        id: check_contribution
        run: python .github/scripts/contribution_check.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_ISSUE_NUMBER: ${{ steps.get_issue_number.outputs.issueNumber }}

      - name: Welcome contributor
        if: steps.check_contribution.outputs.isContributor == false
        run: gh pr comment $PR_URL --body "Welcome! Your contribution is appreciated."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
