name: Welcome
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: Welcome
    runs-on: ubuntu-latest
    steps:
      - name: Install Octokit
        run: npm install @octokit/rest

      - name: Check PR comment history
        id: check_comments
        run: |
          const { Octokit } = require('@octokit/rest');

          const octokit = new Octokit({
            auth: process.env.GITHUB_TOKEN
          });

          const { owner, repo, number } = context.issue;

          const { data: comments } = await octokit.issues.listComments({
            owner,
            repo,
            issue_number: number
          });

          const commentsCount = comments.length;
          console.log(`Total comments: ${commentsCount}`);
          core.setOutput('commentsCount', commentsCount);

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Welcome developer
        if: steps.check_comments.outputs.commentsCount == '0'
        run: gh pr comment $PR_URL --body "Welcome developer!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
